declare module "lucide-react" {
  import { FC, SVGProps, ForwardRefExoticComponent, RefAttributes } from "react"

  type Icon = ForwardRefExoticComponent<
    Omit<SVGProps<SVGSVGElement>, "ref"> & RefAttributes<SVGSVGElement>
  >

  export type LucideIcon = Icon

  export const AlertTriangle: Icon
  export const ArrowDown: Icon
  export const ArrowDownCircle: Icon
  export const ArrowLeft: Icon
  export const ArrowUp: Icon
  export const ArrowUpCircle: Icon
  export const ArrowUpDown: Icon
  export const Ban: Icon
  export const Banknote: Icon
  export const BarChart3: Icon
  export const Bell: Icon
  export const Blocks: Icon
  export const Briefcase: Icon
  export const Building: Icon
  export const Building2: Icon
  export const Calendar: Icon
  export const CalendarIcon: Icon
  export const Check: Icon
  export const CheckCircle: Icon
  export const CheckCircle2: Icon
  export const CheckSquare: Icon
  export const ChevronDown: Icon
  export const ChevronLeft: Icon
  export const ChevronRight: Icon
  export const ChevronsLeft: Icon
  export const ChevronsRight: Icon
  export const ChevronsUpDown: Icon
  export const ChevronUp: Icon
  export const Circle: Icon
  export const Clock: Icon
  export const Columns: Icon
  export const Columns3: Icon
  export const CreditCard: Icon
  export const DollarSign: Icon
  export const Download: Icon
  export const Edit: Icon
  export const Eye: Icon
  export const EyeOff: Icon
  export const FilePlus: Icon
  export const FileSignature: Icon
  export const FileSpreadsheet: Icon
  export const FileText: Icon
  export const Filter: Icon
  export const Gift: Icon
  export const Globe: Icon
  export const History: Icon
  export const Home: Icon
  export const Hospital: Icon
  export const Image: Icon
  export const Inbox: Icon
  export const Info: Icon
  export const Landmark: Icon
  export const LayoutDashboard: Icon
  export const Loader2: Icon
  export const Lock: Icon
  export const LogOut: Icon
  export const Mail: Icon
  export const MapPin: Icon
  export const Menu: Icon
  export const Minus: Icon
  export const Monitor: Icon
  export const Moon: Icon
  export const MoreHorizontal: Icon
  export const PanelLeft: Icon
  export const PanelLeftClose: Icon
  export const Percent: Icon
  export const Phone: Icon
  export const Plus: Icon
  export const Printer: Icon
  export const Receipt: Icon
  export const RefreshCw: Icon
  export const Save: Icon
  export const Search: Icon
  export const Send: Icon
  export const Server: Icon
  export const Settings: Icon
  export const Settings2: Icon
  export const Shield: Icon
  export const ShieldAlert: Icon
  export const Square: Icon
  export const Stamp: Icon
  export const Sun: Icon
  export const ToggleLeft: Icon
  export const ToggleRight: Icon
  export const Trash2: Icon
  export const TrendingDown: Icon
  export const TrendingUp: Icon
  export const Upload: Icon
  export const User: Icon
  export const UserCog: Icon
  export const UserPlus: Icon
  export const Users: Icon
  export const Wallet: Icon
  export const X: Icon
  export const XCircle: Icon
}
